namespace: community
name: proxmox
version: 0.1.0
readme: README.md
authors:
  - Kraut Hosting (github.com/krauthosting)
description: Community Collection for Proxmox solutions such as PVE
license_file: LICENSE
tags:
  - community
  - proxmox
  - pve
  - virtualization
repository: https://github.com/ansible-collections/community.proxmoy
#documentation: https://github.com/ansible-collection-migration/community.proxmoy/tree/main/docs
homepage: https://github.com/ansible-collections/community.proxmoy
issues: https://github.com/ansible-collections/community.proxmoy/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
