# General metadata
title: community.proxmox
changelog_filename_template: ../CHANGELOG.rst
changes_file: changelog.yaml
# Remove changelog fragments from old releases
keep_fragments: false
changes_format: combined
notesdir: fragments

# Sections
new_plugins_after_name: removed_features
prelude_section_name: release_summary
prelude_section_title: Release Summary
trivial_section_name: trivial
sections:
- - major_changes
  - Major Changes
- - minor_changes
  - Minor Changes
- - breaking_changes
  - Breaking Changes / Porting Guide
- - deprecated_features
  - Deprecated Features
- - removed_features
  - Removed Features (previously deprecated)
- - security_fixes
  - Security Fixes
- - bugfixes
  - Bugfixes
- - known_issues
  - Known Issues

# Misc Stuff
changelog_filename_version_depth: 0
mention_ancestor: true
